Jumper Enemy
TheRealTeamFReSh/Bevy-Jam-1 pull request #7
Opened 2022-02-28 05:46 UTC by cdsupina

- added jump function to physics
- add slime enemy spawn functions
- add test enemy startup function

2022-02-28 07:38 UTC, NightlySide requested changes

2022-02-28 07:38 UTC, NightlySide commented on src/runner/backgroundlayer.rs
> +            .add_system(move_background.system());
`.system()` should be removed

2022-03-01 01:02 UTC, tigleym approved these changes
Looks good! Thanks for adding this part in!

2022-03-01 01:28 UTC, cdsupina commented on src/platforms/mod.rs
> +    let collider_size_hy = 24.0 / rapier_config.scale / 2.0;
This is what I'm going to work on next. Randomly stitching together chunks for the runner.

2022-03-01 01:55 UTC, merged